
name: flutter_webview_plugin_example
description: Demonstrates how to use the flutter_webview_plugin plugin.


environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_oauth:
    path: ../

flutter:
  uses-material-design: true